name: zxing_widget
description: A Barcode Generator Widget that can be embedded inside flutter. It uses zxing-dart for all platforms.
version: 1.1.0
repository: https://github.com/shirne/zxing_widget
homepage: https://shirne.github.io/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  zxing_lib: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
